# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:          # [osx and x86_64]
  - 10.13                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]
  
qt:
  - 5
  - 6