{% set version = "4.0.2" %}

package:
  name: qt6-advanced-docking-system
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: b5bf5ebcb77c09ddf92e1e71f78b6598c1fc9311e2cca2dfed3a32ce45f2950d
  patches:
    - 0001-CMakeLists.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('qt6-advanced-docking-system', max_pin='x.x') }}
  missing_dso_whitelist:
  # Follow: https://github.com/conda-forge/deno-feedstock/blob/49611827965b148b4e724b23d4077de17cf4f90b/recipe/meta.yaml#L13-L23
    - /System/Library/Frameworks/Metal.framework/Versions/A/Metal  # [osx]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}          # [not osx]
    - make                           # [not win]
    - ninja                          # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]

  host:
    - qt6-main
    - libxcb                         # [linux]
test:
  commands:
    - if not exist %LIBRARY_BIN%\\qt6advanceddocking.dll exit 1                                     # [win]
    - if not exist %LIBRARY_INC%\\qt6advanceddocking\\ads_globals.h exit 1                          # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\qt6advanceddocking\\qt6advanceddockingConfig.cmake exit 1  # [win]
    - test -f $PREFIX/lib/libqt6advanceddocking${SHLIB_EXT}                                         # [unix]
    - test -f $PREFIX/include/qt6advanceddocking/ads_globals.h                                      # [unix]
    - test -f $PREFIX/lib/cmake/qt6advanceddocking/qt6advanceddockingConfig.cmake                    # [unix]

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPL-2.1-only
  license_file: gnu-lgpl-v2.1.md
  summary: Advanced Docking System for Qt

extra:
  recipe-maintainers:
    - n-elie
