{% set name = "qt5-advanced-docking-system" if qt == '5' else 'qt6-advanced-docking-system' %}
{% set libname = "qtadvanceddocking-qt5" if qt == '5' else 'qtadvanceddocking-qt6' %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: ccd0aa64e5bcfdb58b7ad4dda06b656b90571cfc94cb556dafac4b283ac1bb55

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  missing_dso_whitelist:
  # Follow: https://github.com/conda-forge/deno-feedstock/blob/49611827965b148b4e724b23d4077de17cf4f90b/recipe/meta.yaml#L13-L23
    - /System/Library/Frameworks/Metal.framework/Versions/A/Metal  # [osx]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}          # [not osx]
    - {{ stdlib("c") }}
    - make                           # [not win]
    - ninja                          # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]

  host:
    - qt6-main                       # [qt==6 or qt=='']
    - qt-main                        # [qt==5 or qt=='']
    - libxcb                         # [linux]
test:
  commands:
    - if not exist %LIBRARY_BIN%\\{{ libname }}.dll exit 1                                # [win]
    - if not exist %LIBRARY_INC%\\{{ libname }}\\ads_globals.h exit 1                     # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\{{ libname }}\\{{ libname }}Config.cmake exit 1  # [win]
    - test -f $PREFIX/lib/lib{{ libname }}${SHLIB_EXT}                                    # [unix]
    - test -f $PREFIX/include/{{ libname }}/ads_globals.h                                 # [unix]
    - test -f $PREFIX/lib/cmake/{{ libname }}/{{ libname }}Config.cmake                   # [unix]

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPL-2.1-only
  license_file: gnu-lgpl-v2.1.md
  summary: Advanced Docking System for Qt

extra:
  recipe-maintainers:
    - n-elie
